export const WIDTH = 1280;
export const HEIGHT = 720;
export const MIRROR_X = true;

export const HAND_LM = {
    WRIST: 0,
    INDEX_MCP: 5,
    MIDDLE_MCP: 9,
    MIDDLE_TIP: 12,
    PINKY_MCP: 17,
};

export const FACE_LM = {
    NOSE: 1,
    FOREHEAD: 10,
    CHIN: 152,
    LEFT_EYE_CORNER: 33,
    RIGHT_EYE_CORNER: 263,
    LIP_UPPER: 13,
    LIP_LOWER: 14,
    MOUTH_LEFT: 61,
    MOUTH_RIGHT: 291,
    LIP_OUTER_UPPER: 11,
    LIP_OUTER_LOWER: 17,
};
export const ARKIT_BLENDSHAPES = [
    'browDownLeft',
    'browDownRight',
    'browInnerUp',
    'browOuterUpLeft',
    'browOuterUpRight',
    'cheekPuff',
    'cheekSquintLeft',
    'cheekSquintRight',
    'eyeBlinkLeft',
    'eyeBlinkRight',
    'eyeLookDownLeft',
    'eyeLookDownRight',
    'eyeLookInLeft',
    'eyeLookInRight',
    'eyeLookOutLeft',
    'eyeLookOutRight',
    'eyeLookUpLeft',
    'eyeLookUpRight',
    'eyeSquintLeft',
    'eyeSquintRight',
    'eyeWideLeft',
    'eyeWideRight',
    'jawForward',
    'jawLeft',
    'jawRight',
    'jawOpen',
    'mouthClose',
    'mouthFunnel',
    'mouthPucker',
    'mouthLeft',
    'mouthRight',
    'mouthSmileLeft',
    'mouthSmileRight',
    'mouthFrownLeft',
    'mouthFrownRight',
    'mouthDimpleLeft',
    'mouthDimpleRight',
    'mouthStretchLeft',
    'mouthStretchRight',
    'mouthRollLower',
    'mouthRollUpper',
    'mouthShrugLower',
    'mouthShrugUpper',
    'mouthPressLeft',
    'mouthPressRight',
    'mouthLowerDownLeft',
    'mouthLowerDownRight',
    'mouthUpperUpLeft',
    'mouthUpperUpRight',
    'noseSneerLeft',
    'noseSneerRight',
    'tongueOut'
];
